name: spack mobject+bedrock

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'doc/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install APT Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran-12    
    - name: Checkout Spack
      uses: actions/checkout@v3
      with:
        repository: spack/spack
        path: ./spack
    - name: Checkout mochi-spack-packages
      uses: actions/checkout@v3
      with:
        repository: mochi-hpc/mochi-spack-packages
        path: ./mochi-spack-packages
    - name: Run spack install mobject+bedrock
      run: |
        . ./spack/share/spack/setup-env.sh
        spack repo add ./mochi-spack-packages
        spack install mobject+bedrock
